/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmk.util;

import com.jmk.gui.CustomerListForm;
import java.awt.Toolkit;
import javax.swing.JDialog;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author mulayam
 */
public class PrintDialogUtil extends javax.swing.JDialog {

    /**
     * Creates new form PrintDialogUtil
     */
    public PrintDialogUtil(JDialog parent, boolean modal, JRViewer jRViewer) {
        super(parent, modal);

        initComponents();
        add(jRViewer);
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
